services:
  app:
    build: ./app
    ports:
      - 8000:8000
      - 8081:8081
      - 1234:1234
      - 5678:5678
      - 9876:9876
      - 5544:5544
    volumes:
      - ./app/config:/config
      - ./app/frontend:/frontend
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:cached
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=devops123
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:cached
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:cached
    ports:
      - 3000:3000
      
  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    expose:
      - 9100

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mem  # You can change the storage type as needed
    restart: unless-stopped
