services:
  app:
    build: ./app
    ports:
      - 8000:8000
      - 8081:8081
    volumes:
      - ./app/config:/config
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:cached
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=devops123
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:cached
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:cached
    ports:
      - 3000:3000
      
  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    expose:
      - 9100